version: '3.8'

services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "4651:4651"
    expose:
      - "4651"
    env_file:
      - ./back/.env
    restart: unless-stopped
    volumes:
      - ./back/data:/data
    networks:
      - app-network

  frontend:
    build:
      context: ./nextjs-frontend
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    expose:
      - "5005"
    env_file:
      - ./nextjs-frontend/.env.local
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data:
    driver: local
